#!/bin/bash

NAME=cohere-hackathon
DIR=/home/ubuntu/projects/cohere-hackathon
USER=ubuntu
GROUP=ubuntu
WORKERS=3
TIMEOUT=180
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=/home/ubuntu/.venvs/cohere/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=info

cd $DIR
source $VENV

exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --timeout $TIMEOUT \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
